---
- hosts: all
  vars:
    kafka: kafka_2.11-0.11.0.1
  become: true
  gather_facts: False
  pre_tasks:
    # Ansible requires python2, which is not installed by default on Ubuntu Xenial
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    # action: setup will gather facts after python2 has been installed
    - action: setup
  tasks:

    - name: add java repo
      apt_repository: repo="ppa:webupd8team/java"

    - name: accept java8 license
      debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 value=true vtype=select

    - name: install java8
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default

    - name: install zookeeper
      apt: pkg=zookeeperd state=present

    - name: download kafka
      get_url:
        url: http://www-us.apache.org/dist/kafka/0.11.0.1/{{kafka}}.tgz
        dest: /tmp/{{kafka}}.tgz
        checksum: sha256:0da77e1e542cf097d6025309bc996c10ceda394839c041934b86d8729ab574f1

    - name: create kafka directory
      file:
        path: /opt/kafka
        state: directory

    - name: extract kafka .tgz into /opt/kafka
      unarchive:
        copy: no
        src: /tmp/{{kafka}}.tgz
        dest: /opt/kafka
        
    - name: install kafka systemd service
      template: src=templates/kafka.j2 dest=/etc/systemd/system/kafka.service
      
    - name: stop kafka
      systemd: state=stopped name=kafka
      ignore_errors: yes      

    - name: start kafka
      systemd: state=started enabled=yes name=kafka daemon_reload=yes
