---
- hosts: all
  become: true
  gather_facts: False
  pre_tasks:
    # Ansible requires python2, which is not installed by default on Ubuntu Xenial
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    # action: setup will gather facts after python2 has been installed
    - action: setup
  tasks:

    - include: build_viaxch.yml

    - name: create log directory
      file: path=/var/log/trade/ state=directory

    # using named groups due to ansible munging backrefs next to numbers (http://www.handverdrahtet.org/2016/01/ansible-using-numbered-backreference.html)
    - name:
      shell: perl -i -p0e 's/{{ item.regexp }}/{{ item.replace }}/s' {{root_dir}}/accessws/config.json
      with_items:
          - { regexp: '(?<one>"matchengine": \{[^\{]*"addr": \[[^\{]*"tcp@)(127.0.0.1)(?<three>:7316")',
              replace: '$+{one}{{match_host}}$+{three}' }
          - { regexp: '(?<one>"marketprice": \{[^\{]*"addr": \[[^\{]*"tcp@)(127.0.0.1)(?<three>:7416")',
              replace: '$+{one}{{price_host}}$+{three}' }
          - { regexp: '(?<one>"readhistory": \{[^\{]*"addr": \[[^\{]*"tcp@)(127.0.0.1)(?<three>:7424")',
              replace: '$+{one}{{data_host}}$+{three}' }          
          - { regexp: '(?<one>"deals": \{[^\{]*"brokers": ")(127.0.0.1)(?<three>:9092",)',
              replace: '$+{one}{{kafka_host}}$+{three}' }
          - { regexp: '(?<one>"orders": \{[^\{]*"brokers": ")(127.0.0.1)(?<three>:9092",)',
              replace: '$+{one}{{kafka_host}}$+{three}' }
          - { regexp: '(?<one>"balances": \{[^\{]*"brokers": ")(127.0.0.1)(?<three>:9092",)',
              replace: '$+{one}{{kafka_host}}$+{three}' }
          - { regexp: '(?<one>"auth_url": ")([^"]*)(?<three>",)',
              replace: '$+{one}{{auth_url | regex_replace("/", "\/")}}$+{three}' }
          - { regexp: '(?<one>"alert": \{[^\{]*"addr": ")(127.0.0.1)(?<three>:4444")',
              replace: '$+{one}{{alert_host}}$+{three}' }
          - { regexp: '(?<one>"svr": \{[^\{]*"bind": \[[^\]]*")(stream@\/tmp\/accessws.sock)',
              replace: '$+{one}tcp\@0.0.0.0:8090' }

    - name: install accessws systemd service
      template: src=templates/accessws.j2 dest=/etc/systemd/system/accessws.service

    - name: stop accessws
      systemd: state=stopped name=accessws
      ignore_errors: yes

    - name: start accessws
      systemd: state=started enabled=yes name=accessws daemon_reload=yes
